import { describe, it } from 'vitest'
import * as fc from 'fast-check'
import { buildOAuthUrl } from './buildOAuthUrl'

/**
 * Feature: meta-report, Property 1: OAuth URL Permission Integrity
 * Validates: Requirements 2.1
 * 
 * For any OAuth authorization URL generated by the system, the URL SHALL 
 * contain both `ads_read` and `business_management` permission scopes.
 */
describe('OAuth URL Property Tests', () => {
  it('Property 1: OAuth URL Permission Integrity - URL contains required scopes', () => {
    fc.assert(
      fc.property(
        fc.string({ minLength: 1, maxLength: 50 }), // clientId
        fc.webUrl(), // redirectUri
        (clientId, redirectUri) => {
          const { url } = buildOAuthUrl({ clientId, redirectUri })
          
          // URL must contain both required scopes
          const hasAdsRead = url.includes('ads_read')
          const hasBusinessManagement = url.includes('business_management')
          
          return hasAdsRead && hasBusinessManagement
        }
      ),
      { numRuns: 20 }
    )
  })

  it('Property 1: OAuth URL Permission Integrity - URL is valid Facebook OAuth URL', () => {
    fc.assert(
      fc.property(
        fc.string({ minLength: 1, maxLength: 50 }),
        fc.webUrl(),
        (clientId, redirectUri) => {
          const { url } = buildOAuthUrl({ clientId, redirectUri })
          
          return url.startsWith('https://www.facebook.com/v18.0/dialog/oauth')
        }
      ),
      { numRuns: 20 }
    )
  })

  it('Property 1: OAuth URL Permission Integrity - state is generated and included', () => {
    fc.assert(
      fc.property(
        fc.string({ minLength: 1, maxLength: 50 }),
        fc.webUrl(),
        (clientId, redirectUri) => {
          const { url, state } = buildOAuthUrl({ clientId, redirectUri })
          
          // State should be non-empty and included in URL
          return state.length > 0 && url.includes(`state=${state}`)
        }
      ),
      { numRuns: 20 }
    )
  })

  it('Property 1: OAuth URL Permission Integrity - custom state is preserved', () => {
    fc.assert(
      fc.property(
        fc.string({ minLength: 1, maxLength: 50 }),
        fc.webUrl(),
        fc.hexaString({ minLength: 16, maxLength: 32 }),
        (clientId, redirectUri, customState) => {
          const { url, state } = buildOAuthUrl({ clientId, redirectUri, state: customState })
          
          return state === customState && url.includes(`state=${customState}`)
        }
      ),
      { numRuns: 20 }
    )
  })
})
